import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const links = [
    {
      href: "/",
      label: "Home",
      icon: "/images/home.png",
    },
    {
      href: "/",
      label: "Doctors",
      icon: "/images/doctor.png",
    },
    {
      href: "/",
      label: "Specialties",
      icon: "/images/specialty.png",
    },
    {
      href: "/logout",
      label: "Logout",
      icon: "/images/logout.png",
    },
  ];

  return (
    <html lang="en">
      <body className="relative">
        <header className="min-h-screen flex min-w-[1vw] left-0 bg-blue-100 group overflow-hidden transition-all z-[2] fixed hover:min-w-[20vw]">
          <nav className="flex justify-center flex-col w-full">
            <ul className="space-y-2">
              {links.map((link) => (
                <li key={link.href}>
                  <button className="flex w-full items-center p-4 hover:bg-white">
                    <img className="h-8 w-8" src={link.icon} alt={link.label} />{" "}
                    <p className="ml-4 hidden group-hover:block">
                      {link.label}
                    </p>
                  </button>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        <main className="absolute top-0 right-0 min-h-screen w-[95vw]">
          {children}
        </main>
      </body>
    </html>
  );
}
