import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const links = [
    {
      href: "/",
      label: "Home",
      icon: "/images/home.png",
    },
    {
      href: "/",
      label: "Doctors",
    },
    {
      href: "/",
      label: "Specialties",
    },
    {
      href: "/logout",
      label: "Logout",
    },
  ];

  return (
    <html lang="en">
      <body className="relative">
        <header className="min-h-screen flex w-[5vw] left-0 bg-blue-100">
          <nav className="flex justify-center flex-col">
            <ul>
              {links.map((link) => (
                <li key={link.href}>
                  <button>{link.label}</button>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        <main className="absolute top-0 right-0 min-h-screen w-[95vw]">
          {children}
        </main>
      </body>
    </html>
  );
}
