import "./globals.css";

export const metadata = {
  title: "HealthHealthABC",
  description: "Generated by create next app",
  authors: {
    name: "ChatChatABC Philippines Inc.",
    url: "https://chatchatabc.com",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        {/* Nav Bar */}
        <header className="bg-blue-50">
          {/* Nav Menu */}
          <nav className="container flex mx-auto px-4 lg:px-8">
            {/* Logo */}
            <a className="py-4 inline-block" href="/">
              <p>Logo</p>
            </a>

            {/* Nav Links */}
            <ul className="ml-auto flex items-center space-x-8">
              <li className="">
                <a href="/login">Login</a>
              </li>
              <li className="">
                <a href="/login">Login</a>
              </li>
              <li className="">
                <a href="/login">Login</a>
              </li>
            </ul>
          </nav>
        </header>

        {/* Main Content */}
        {children}

        {/* Footer */}
        <footer></footer>
      </body>
    </html>
  );
}
