import Navbar from "./Navbar";
import "./globals.css";
import Notification from "@/app/Notification";

export const metadata = {
  title: "HealthHealthABC",
  description: "Generated by create next app",
  authors: {
    name: "ChatChatABC Philippines Inc.",
    url: "https://chatchatabc.com",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        {/* Nav Bar */}
        <Navbar />

        <Notification />

        {/* Main Content */}
        {children}

        {/* Footer */}
        <footer></footer>
      </body>
    </html>
  );
}
